import { NextResponse, type NextRequest } from "next/server";
import type { EmailOtpType } from "@supabase/supabase-js";

import { createClient } from "@/lib/supabase/server";
import { siteUrl } from "@/lib/seo";

/**
 * A one time email token, exchanged for a session on this origin.
 *
 * The office sends a link that points here rather than at Supabase. Going
 * through Supabase's own verifier costs two things: it forwards only to URLs on
 * the project's redirect allow list, silently dropping anyone else on the site
 * root, and a link generated by an admin has no PKCE verifier behind it, so it
 * comes back with the tokens in a fragment that never reaches a server. Here
 * the token is verified in one call, the session cookies are written, and the
 * rider lands on the page that asks them for a password.
 *
 * `/auth` is outside the proxy's matcher, so nothing rewrites this path. The
 * destination is prefix-less on purpose: the proxy picks the locale up when the
 * browser follows the redirect.
 */
const TYPES: EmailOtpType[] = [
  "recovery",
  "invite",
  "signup",
  "magiclink",
  "email_change",
  "email",
];

const isType = (value: string | null): value is EmailOtpType =>
  Boolean(value) && TYPES.includes(value as EmailOtpType);

/** Only a path on this site, so a crafted link cannot bounce anyone elsewhere. */
const safePath = (next: string | null, fallback: string) =>
  next && next.startsWith("/") && !next.startsWith("//") ? next : fallback;

export async function GET(request: NextRequest) {
  const { searchParams } = request.nextUrl;

  const tokenHash = searchParams.get("token_hash");
  const type = searchParams.get("type");
  const next = safePath(searchParams.get("next"), "/account");

  if (!tokenHash || !isType(type)) {
    return NextResponse.redirect(`${siteUrl}${next}?error=auth`);
  }

  const supabase = await createClient();
  const { error } = await supabase.auth.verifyOtp({ type, token_hash: tokenHash });

  return NextResponse.redirect(`${siteUrl}${error ? `${next}?error=auth` : next}`);
}
